<?php 
return array (
  'site_name' => '微通汇微信营销系统',
  'site_title' => '微通汇,微信营销系统,微信机器人,微信自动回复,免费微信建站',
  'site_logo' => 'http://gooraye02.qiniudn.com/gr_%E5%8F%A4%E7%9D%BF.png',
  'site_url' => 'http://114.215.198.83',
  'site_my' => '微通汇',
  'server_key' => 'u8UAepm7wNYKh2ypXDTrn3o8',
  'server_topdomain' => 'http://114.215.198.83/',
  'connectout' => '',
  'ischeckuser' => 'true',
  'reg_needmp' => 'false',
  'reg_groupid' => '4',
  'reg_validdays' => '3000',
  'router_key' => '',
  'ipc' => '浙ICP备14015469号-1',
  'site_qq' => '2966442390',
  'site_mp' => '',
  'baidu_map_api' => 'u8UAepm7wNYKh2ypXDTrn3o8',
  'site_email' => 'admin@gooraye.com',
  'keyword' => '古睿，微通汇，微信营销系统,微网站,微信营销,微网站开发,微网站代理,微网站制作,微信网站,微信3G网站,微信APP,企业微信,企业微网站,微信公众号,微信互动',
  'content' => '微通汇是由绍兴古睿信息科技有限公司研发的一款基于微信营销的产品，可以帮助企业快速通过微信获得生意，推广企业品牌。">',
  'countsz' => '',
  'copyright' => 'Copyright © 2013-2014 gooraye 版权所有',
);